apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"e6:73:ba:5d:54:a1"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    flannel.alpha.coreos.com/public-ip: 192.168.15.10
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2022-12-21T07:12:02Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: k8s-master
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: k8s-master
  resourceVersion: "40228"
  uid: 491a92a3-5ec6-491b-91ce-4e3a87d4d8a5
spec:
  podCIDR: 10.144.0.0/12
  podCIDRs:
  - 10.144.0.0/12
status:
  addresses:
  - address: 192.168.15.10
    type: InternalIP
  - address: k8s-master
    type: Hostname
  allocatable:
    cpu: "4"
    ephemeral-storage: "22662763278"
    hugepages-2Mi: "0"
    memory: 8037952Ki
    pods: "110"
  capacity:
    cpu: "4"
    ephemeral-storage: 24590672Ki
    hugepages-2Mi: "0"
    memory: 8140352Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2022-12-21T07:19:23Z"
    lastTransitionTime: "2022-12-21T07:19:23Z"
    message: Flannel is running on this node
    reason: FlannelIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2022-12-21T08:20:32Z"
    lastTransitionTime: "2022-12-12T13:02:34Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-12-21T08:20:32Z"
    lastTransitionTime: "2022-12-12T13:02:34Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-12-21T08:20:32Z"
    lastTransitionTime: "2022-12-12T13:02:34Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-12-21T08:20:32Z"
    lastTransitionTime: "2022-12-21T07:19:17Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - registry.aliyuncs.com/google_containers/etcd@sha256:dd75ec974b0a2a6f6bb47001ba09207976e625db898d1b16735528c009cb171c
    - registry.aliyuncs.com/google_containers/etcd:3.5.6-0
    sizeBytes: 102542580
  - names:
    - registry.aliyuncs.com/google_containers/kube-apiserver@sha256:d230a0b88a3daf14e4cce03b906b992c8153f37da878677f434b1af8c4e8cc75
    - registry.aliyuncs.com/google_containers/kube-apiserver:v1.26.0
    sizeBytes: 35317868
  - names:
    - registry.aliyuncs.com/google_containers/kube-controller-manager@sha256:26e260b50ec46bd1da7352565cb8b34b6dd2cb006cebbd2f35170d50935fb9ec
    - registry.aliyuncs.com/google_containers/kube-controller-manager:v1.26.0
    sizeBytes: 32244989
  - names:
    - registry.aliyuncs.com/google_containers/kube-proxy@sha256:1e9bbe429e4e2b2ad32681c91deb98a334f1bf4135137df5f84f9d03689060fe
    - registry.aliyuncs.com/google_containers/kube-proxy:v1.26.0
    sizeBytes: 21536465
  - names:
    - docker.io/rancher/mirrored-flannelcni-flannel@sha256:ec0f0b7430c8370c9f33fe76eb0392c1ad2ddf4ccaf2b9f43995cca6c94d3832
    - docker.io/rancher/mirrored-flannelcni-flannel:v0.20.2
    sizeBytes: 20908409
  - names:
    - registry.aliyuncs.com/google_containers/kube-scheduler@sha256:34a142549f94312b41d4a6cd98e7fddabff484767a199333acb7503bf46d7410
    - registry.aliyuncs.com/google_containers/kube-scheduler:v1.26.0
    sizeBytes: 17484038
  - names:
    - registry.aliyuncs.com/google_containers/coredns@sha256:8e352a029d304ca7431c6507b56800636c321cb52289686a581ab70aaa8a2e2a
    - registry.aliyuncs.com/google_containers/coredns:v1.9.3
    sizeBytes: 14837849
  - names:
    - quay.io/jetstack/cert-manager-cainjector@sha256:b5657161d2c2f74ab292da4cbaba3923bc74112525f70c3d884fb3c6ef83c303
    - quay.io/jetstack/cert-manager-cainjector:v1.10.1
    sizeBytes: 12201630
  - names:
    - docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin@sha256:28d3a6be9f450282bf42e4dad143d41da23e3d91f66f19c01ee7fd21fd17cb2b
    - docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0
    sizeBytes: 3821285
  - names:
    - registry.aliyuncs.com/google_containers/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
    - registry.aliyuncs.com/google_containers/pause:3.9
    sizeBytes: 321520
  - names:
    - registry.aliyuncs.com/google_containers/pause@sha256:9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d
    - registry.aliyuncs.com/google_containers/pause:3.8
    sizeBytes: 311286
  nodeInfo:
    architecture: amd64
    bootID: 8a4afb49-ba37-40f0-80e5-e6a9f4a0f45c
    containerRuntimeVersion: containerd://1.6.12
    kernelVersion: 5.15.0-56-generic
    kubeProxyVersion: v1.26.0
    kubeletVersion: v1.26.0
    machineID: fe70c41cd4f74ce89012ec5713b161ab
    operatingSystem: linux
    osImage: Ubuntu 22.04.1 LTS
    systemUUID: 8a94a780-9fc0-df4d-96e4-5123d7d681f0
